### PR TITLE
Update visualizing-blast-scores-with-RStudio.md

### PR DESCRIPTION
**Pull request by taylorreiter**
Add some R code to visualize the shmlast output. Histograms are rough, and might need to be improved. 

I chose base R plotting, I could add ggplot but that seems like unnecessary complexity. 

### Things to check off before merging:

- [x] Files are listed in `toc.rst` so they will show up on the side bar.
- [x] The tutorial assumes we're starting from a blank `Ubuntu 16.04` image on Jetstream.

### CODE REVIEW

**Comment by ctb** [comment]
depends a bit on PR #210

**Comment by upendrak** [comment]
@taylorreiter @ctb `dim(surveys)` needs to be changed to `dim(shmlast_out)`

**Comment by ctb** [comment]
> @taylorreiter @ctb `dim(surveys)` needs to changed to `dim(shmlast_out)` 

this should be in the latest push, no?

**Comment by ctb** [comment]
@taylorreiter approves this PR!

**Pull request merged**
