### PR TITLE
update schedule etc for thursday and friday

### PR DESCRIPTION
**Pull request by ctb**
See https://github.com/ngs-docs/angus/blob/fix/thursday/index.md#thursday-day-11-rnaseq

### Things to check off before merging:

- [x] Files are listed in `toc.rst` so they will show up on the side bar.
- [x] Files are listed in `index.rst` appropriately
- [x] The tutorial assumes we're starting from a blank `Ubuntu 16.04` image on Jetstream.

### CODE REVIEW

**Comment by fpsom** [comment]
@ctb Would it be ok if I didn't do the morning session on Friday, so that I can listen to Rob & Mike's talk? Everything else looks good to me.

**Comment by ctb** [comment]
yep! maybe you can do afternoon session and I will attend rob and mike's
session?

On Thu, Jul 06, 2017 at 04:44:16PM +0000, Fotis E. Psomopoulos wrote:
> @ctb Would it be ok if I didn't do the morning session on Friday, so that I can listen to Rob & Mike's talk? Everything else looks good to me.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/ngs-docs/angus/pull/291#issuecomment-313452515
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by fpsom** [comment]
Sure, sounds perfect!

**Comment by johnsolk** [comment]
lgtm

**Pull request merged**
