### PR TITLE
A few fixes to the Chip-Seq lesson

### PR DESCRIPTION
**Pull request by HadrienG**
We install `bowtie2` before moving to the `ChIP-seq` dir. Modified the path to reflect that.

Also fixed the `samtools sort` commands

### CODE REVIEW

**Comment by HadrienG** [comment]
cc @fpsom and @ctb for review. But maybe wait for lunch break to not confuse the students (they'd have to refresh the page etc...)?

**Comment by ctb** [comment]
does the samtools sort -o work with old versions of samtools?

**Comment by ctb** [comment]
it doesn't seem to - what's your samtools version @HadrienG ?

**Comment by ctb** [comment]
we install `Version: 0.1.19-96b5f2294a`

**Comment by HadrienG** [comment]
Good point, we installed `1.5` with linuxbrew in an earlier tutorial and I wasn't on a fresh instance

On a fresh instance, `pip install MACS2` seems to fail (at least for @bluegenes )

**Comment by HadrienG** [comment]
Reverted the `samtools sort` changes so the tutorial is self-contained and works on a new instance.

I guess it's the simplest we'll debug the students with samtools 1.5 on a case by case basis

**Comment by ctb** [comment]
included in #298

**Pull request closed without merging**
