### PR TITLE
Creating RMarkdown lesson outline and file

### PR DESCRIPTION
**Pull request by marschmi**
(Please put a direct link to the updated tutorial(s) on the PR branch here,
so we can look at them while reviewing!)

### Things to check off before merging:

- [x] Files are listed in `toc.rst` so they will show up on the side bar.
- [ ] Files are listed in `index.rst` appropriately
- [x] The tutorial assumes we're starting from a blank `Ubuntu 16.04` image on Jetstream.

### CODE REVIEW

**Comment by marschmi** [comment]
@taylorreiter and I are currently developing this lesson and aren't sure *when* this lesson will be in the schedule. 

**Not yet ready for review or merge**

**Comment by taylorreiter** [comment]
@ctb ready for review and merge!

Please check the `wget` command path to download the file...I think it will work after merge but I want to make sure my thought process is correct

https://github.com/ngs-docs/angus/blob/marschmi-patch-1/rmarkdown_rnaseq.md

**Comment by fpsom** [comment]
@taylorreiter the table under Bibliography has some issues..

**Comment by taylorreiter** [comment]
@fpsom @marschmi is on it!

**Comment by fpsom** [comment]
Minor point: will a final version of the Rmd file be available for direct download?

**Comment by marschmi** [comment]
Yes @fpsom !  We use a wget to get the data and the rmd and html are there ! :)

**Comment by shannonekj** [comment]
this link doesn't load  http://www.rpubs.com/your_username/name_of_your_choice @taylorreiter @marschmi

**Comment by marschmi** [comment]
@shannonekj  it shouldn't load!  They will need their own username and the name of their own page - this is an example of what the link would be

**Comment by shannonekj** [comment]
@marschmi yeah oversight on my part-- disregard!

**Pull request merged**
