### PR TITLE
upd rstudio server version - ready for review + merge

### PR DESCRIPTION
**Pull request by bluegenes**
just an update to rstudio server version.

Would someone mind running through this before merging? I can get the server running, but then can't log in with my XSEDE username/pw...

### Things to check off before merging:

- [ ] Files are listed in `toc.rst` so they will show up on the side bar.
- [ ] The tutorial assumes we're starting from a blank `Ubuntu 16.04` image on Jetstream.

### CODE REVIEW

**Comment by upendrak** [comment]
@bluegenes for some strange reason the XSEDE login/pw are not working for logging into Rstudio. I found a way around though. Change your password in the VM using the following 
```
 sudo passwd <xsdede username>
Enter new UNIX password: 
Retype new UNIX password: 
```
And then use the updated/new password to login to Rstudio. This pw is temporary and is specific to this VM. Your original XSEDE pw remains the same

**Comment by bluegenes** [comment]
Nice - this worked for me.

**Comment by bluegenes** [comment]
I'll add this into the bottom of the tutorial for now.

**Comment by ctb** [comment]
ready to merge?

**Comment by bluegenes** [comment]
yep!

**Review by ctb — APPROVED** [review]
💯

**Pull request merged**
