### PR TITLE
R Lesson: Fixing markdown render & small fixes

### PR DESCRIPTION
**Pull request by marschmi**
PR author:
- [x] pull request is ready for review & merge

### CODE REVIEW

**Comment by marschmi** [comment]
@taylorreiter @rociotmartinez I noticed that the ggplots aren't rendering correctly in the lesson. :/ 
Will need to check for this tomorrow.

**Review by taylorreiter — APPROVED** [review]
thanks @marschmi! Merging now and we can fix ggplots later

**Comment by AstrobioMike** [comment]
So unfortunately it seems readthedocs doesn’t work with r-markdown. So it’s not able to render that version, it’s trying to render the regular markdown version, which doesn’t have the images in there. But I’m on that now :)

**Comment by taylorreiter** [comment]
whoops ok! I'll wait to merge.

We knew it wouldn't render the Rmd, so we knitted the Rmd to md using the knit function, and that's what's rendering. I think we thought it would retain the images, but those need to be referenced from files.

**Comment by AstrobioMike** [comment]
Oh, and we can’t tell it to use the .html file that’s in the main directory. What it does is finds all the .md files, builds the site, and puts it all in an html subdirectory created at that moment, and then puts those up :/

**Comment by taylorreiter** [comment]
Ya! The html and Rmd file in the repo are not doing anything. They're there as a reference, and I think we used the html to test something

**Comment by marschmi** [comment]
The render problems still exist: https://angus.readthedocs.io/en/2019/R_Intro_Lesson.html

**Pull request merged**
