### PR TITLE
Update running-command-line-blast.md

### PR DESCRIPTION
**Pull request by upendrak**
(Please put a direct link to the updated tutorial(s) on the PR branch here,
so we can look at them while reviewing!)

http://angus.readthedocs.io/en/2018/running-command-line-blast.html

### Things to check off before merging:

- [x] Files are listed in `toc.rst` so they will show up on the side bar.
- [x] Files are listed in `index.rst` appropriately
- [x] The tutorial assumes we're starting from a blank `DIBSI 2018` image on Jetstream.

### CODE REVIEW

**Review by fpsom — COMMENTED** [review]
I would not delete the directories in the listing. They actually did show when running the commands, so completely removing them might be confusing...

**Comment by upendrak** [comment]
But those directories are in the user's home directory and the users are currently in `blast` directory .

**Comment by fpsom** [comment]
@upendrak you are right of course. I have no idea why I remember (I think) seeing the directories as well, but given the previous commands it does make sense...

**Review by fpsom — APPROVED** [review]
LGTM

**Pull request merged**
