### PR TITLE
Update Wednesday's Schedule & Typos in index.md

### PR DESCRIPTION
**Pull request by marschmi**
PR author:
- [ ] pull request is ready for review & merge

### CODE REVIEW

**Comment by taylorreiter** [comment]
@marschmi I think the title of Amanda's talk is purposely "How to statistics"

**Comment by marschmi** [comment]
Oops! I didn't realize. I still think we need to add the shell to the morning schedule so people don't feel like their "behind"

**Review by taylorreiter — APPROVED** [review]
lgtm

**Comment by taylorreiter** [comment]
I totally agree, thanks @marschmi!

**Pull request merged**
