### PR TITLE
Update yeast.salmon.R

### PR DESCRIPTION
**Pull request by taylorreiter**
change the MDS label identifiers to something more informative and intuitive than (A, B, E, C, D, F)

The link will also need to be updated on the tutorial (it links to a @elijahlowe branch right now) but I don't how to put these both in one PR and maintain fidelity of the link...

### Things to check off before merging:

- [x] Files are listed in `toc.rst` so they will show up on the side bar.
- [x] The tutorial assumes we're starting from a blank `Ubuntu 16.04` image on Jetstream.

### CODE REVIEW

**Comment by taylorreiter** [comment]
@ctb

**Comment by ctb** [comment]
you have a branch here now, so you can replace elijahlowe-patch-1 with
taylorreiter-patch-4 or whatever.  the URLs should work if you test 'em
out.

**Comment by ctb** [comment]
that is, you can use the branch name of the PR.

**Comment by ctb** [comment]
now part of #238

**Pull request closed without merging**
