### PR TITLE
Update boot.md

### PR DESCRIPTION
**Pull request by AstrobioMike**
updating user name information and link to instructions page for logging into cloud instance through ssh

PR author:
- [ ] pull request is ready for review & merge

Things to check:

- [ ] tutorial resets working directory at beginning with a `cd ~/``
- [ ] tutorial contains relevant `conda install -y` commands at the beginning
- [ ] tutorial links to previous tutorial (at top) and next tutorial (at bottom)
- [ ] tutorial has learning objectives at top

### CODE REVIEW

**Review by upendrak — COMMENTED** [review]
Is there a reason why the paragraph referring to what a n image has been deleted?

**Comment by AstrobioMike** [comment]
I am confused as to how this happened, but i actually didn't make that change. It says they were made june 22nd by titus in the compare changes page. So i think that was his call

**Comment by ctb** [comment]
what did I do now?

**Comment by AstrobioMike** [comment]
Section 5.7 of the booting the jetstream page (http://angus.readthedocs.io/en/2018/jetstream/boot.html) used to have a a paragraph explanation of what an disk image is, but it was removed June 22nd when you added the information on choosing the proper disk image. Somehow that change showed up in the PR i just sent in. But it was already removed and not on the rendered version of the site before my changes here

**Comment by ctb** [comment]
huh. ok :)

**Review by upendrak — APPROVED** [review]
LGTM

**Pull request merged**
