### PR TITLE
add installation of samtools to variant calling lessons

### PR DESCRIPTION
**Pull request by jessicalumian**
added samtools install pulled from ggi course materials linked at top

### Things to check off before merging:

- [x] Files are listed in `toc.rst` so they will show up on the side bar.
- [x] The tutorial assumes we're starting from a blank `Ubuntu 16.04` image on Jetstream.

### CODE REVIEW

**Comment by jessicalumian** [comment]
btw there are problems further down with this lesson (the next one I'm seeing is a EOF absent message from sorting the bam file), but I'm about to lose my wifi for the night so I can't do anymore! I'll make an issue for this but it might be lost in the sea :)

**Review by bluegenes — APPROVED** [review]
looks good

**Comment by ctb** [comment]
@jessicamizzi are you using an m1.medium or m1.small? out-of-space errors manifest as EOFs

**Comment by jessicalumian** [comment]
yeah I just realized I was using tiny, I'm running it on medium now with no problem. also I see samtools was installed at the top but not formatted correctly

**Comment by ctb** [comment]
w00t thank you!

**Review by ctb — APPROVED** [review]
PR looks good! Merging.

**Pull request merged**
