### PR TITLE
make index link text more consistent, add links

### PR DESCRIPTION
**Pull request by charlesreid1**
adding links to slides/notes, making link text formatting more consistent, adding Torsten's slides

PR author:
- [x] pull request is ready for review & merge

Things to check: (N/A, no tutorials modified)

- [] ~tutorial resets working directory at beginning with a `cd ~/``~
- [] ~tutorial contains relevant `conda install -y` commands at the beginning~
- [] ~tutorial links to previous tutorial (at top) and next tutorial (at bottom)~
- [] ~tutorial has learning objectives at top~

### CODE REVIEW

**Comment by charlesreid1** [comment]
bump

**Comment by charlesreid1** [comment]
bump

**Comment by charlesreid1** [comment]
bump

**Review by sateeshperi — APPROVED** [review]
lgtm

**Pull request merged**
